# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vertexauth',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/vertexauth',
                'lib_path': 'vertexauth'},
  'syms': { 'vertexauth.core': { 'vertexauth.core.get_anthropic_client': ('core.html#get_anthropic_client', 'vertexauth/core.py'),
                                 'vertexauth.core.get_claudette_client': ('core.html#get_claudette_client', 'vertexauth/core.py')}}}
