# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vertexauth',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/vertexauth',
                'lib_path': 'vertexauth'},
  'syms': {'vertexauth.core': {'vertexauth.core.foo': ('core.html#foo', 'vertexauth/core.py')}}}
