"""Tiny helper to authenticate Claudette to Vertex AI"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['SUPERKEY_DEFAULT_PATH', 'get_anthropic_client', 'get_claudette_client']

# %% ../nbs/00_core.ipynb 2
import json, os
from pathlib import Path
from fastcore.utils import *

from anthropic import AnthropicVertex, AsyncAnthropicVertex
from claudette import Client, AsyncClient


# %% ../nbs/00_core.ipynb 28
SUPERKEY_DEFAULT_PATH = Path.home() / ".config" / "vertexauth" / "default" / "superkey.json"

# %% ../nbs/00_core.ipynb 34
def get_anthropic_client(asink=False,anthropic_kwargs=None):
    d = json.loads(SUPERKEY_DEFAULT_PATH.read_text())
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(SUPERKEY_DEFAULT_PATH)
    os.environ["GOOGLE_CLOUD_PROJECT"]           = d['project_id']
    anthropic_kwargs = anthropic_kwargs or {}
    AV = AnthropicVertex if not asink else AsyncAnthropicVertex
    return AV(region=d['region'],project_id=d['project_id'], **anthropic_kwargs)    

def get_claudette_client(vertex_model='claude-3-5-sonnet-v2@20241022', 
                         asink=False, anthropic_kwargs=None):
    vertex_cli = get_anthropic_client(asink, anthropic_kwargs)
    if asink: return AsyncClient(vertex_model, vertex_cli)
    else: return Client(vertex_model, vertex_cli)
